### ISSUE TITLE
WButton1 caption 

### ISSUE THREAD

**Issue by majer2022** [pascaldragon/Pas2JS_Widget#25]
I have a problem with the name of the buttons after adding Polish language characters, the website gets a completely different name 
for example 
` object WButton9: TWButton
        Left = 290
        Height = 25
        Top = 334
        Width = 75
        Caption = 'źle'
        TabOrder = 4
        OnClick = WButton9Click     
`
on the website gets the button name 
Åºle

when under the button adds 
`Wbutton9.Caption:='źle';`
and I press the button, everything is displayed correctly

**Comment by pascaldragon** [comment]
This is the same issue as #22, so I'm closing this one.
