### ISSUE TITLE
Error: Incompatible type for arg no. 2: Got "open array", expected "array of const" (dialogs.pas)

### ISSUE THREAD

**Issue by cpicanco** [pascaldragon/Pas2JS_Widget#27]
Hi, I am trying to compile a `Web Gui Application (Pas2JS)` in Lazarus (trunk) and I am getting this error in line  507 of dialogs.pas:

```pascal
procedure ShowMessageFmt(const AMessage: string; const AArguments: array of JSValue);
begin
  ShowMessage(Format(AMessage, AArguments));
end;    
```

What is happening here? How can I fix it? I can compile after commenting the line, but I really want to make sure I am doing the right initial setup before moving any further.

**Comment by cpicanco** [comment]
Note: First I downloded the `WCL` available here. Then I tried the one available in the `ccr` folder.

**Comment by cpicanco** [comment]
Also, pas2js version says:

```
Pas2JS Compiler version 2.3.1 [2022/11/28] for Win64 x86_64
```

**Comment by pascaldragon** [comment]
Sorry that it took quite some time, but it's fixed now 😅

**Comment by bbrtj** [comment]
Got this again today when compiling wcl.lpk from master branch on fpc 3.2.2 and lazarus 3.8 (and current version of pas2js from gitlab) on FreeBSD. Modifying manually to `array of const` helped.

Edit: Actually, my pas2js version was wrong. Needed to use fixes_3_0 branch. That fixed other problem I had, but still could not compile wcl.lpk unchanged. So it's not working for me on both `main` branch and `fixes_3_0` branch of pas2js.
